server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka 服务端的实例名称:
  #    hostname: localhost #eureka 服务端的实例名称:

  #register-with-eureka: false 表示不向注册中心注册自己
  #fetch-registry: false 表示 自己端 就是注册中心， 职责就是维护服务实例，并不需要去检索服务
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与 Eureka Server 交互地址查询服务 和 注册服务 都需要依赖这个地址

